export  const featureList=[
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd274188f3ac56ef461c73/Essentials.jpg",
     "h3Name":"Essentials",
      "span":"6/",
    "p":"42 features ",
    "bundleCount":"6 /42",
    "featureHeadH3":"Features (6/42)",
    "featureTextH3":"Essentials",
    "featureTextP":"Apps like Tinder, Yelp and 84 more also have this bundle.","id":"left_0","checkId":"checkfeature_0",
    "featureList":[
        {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/icon/583e64de5cba2a4656829cd3/FacebookLogin.svg",
         "featureNameH3":"Facebook Login",
        "featureNameP":"0.4 week",
         "featureNameH4":"₹7,630.57","id":"fcheck_0"},
         {"img":"https://studio.builder.ai/assets/images/featureDefault.png","featureNameH3":"Forgot Password","featureNameP":"1.5 Weeks","featureNameH4":"₹20,935.03","id":"fcheck_1"},
         {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/icon/59fd165988f3ac61106b35a7/FreeTrial.svg","featureNameH3":"Free Trial","featureNameP":"0.8 Week","featureNameH4":"₹14,273.88","id":"fcheck_2,"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
         {"img":"","featureNameH3":"","featureNameP":"","featureNameH4":"","id":"fcheck_0"},
    ] },
    {
        "img":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd272f88f3ac56ef461c6d/Social.jpg",
        "h3Name":"Social","span":"5 /","p":"59 features","bundleCount":"5/59","featureHeadH3":"Features (5/59)","featureTextH3":"Social","featureTextP":"Apps like Tinder, Yelp and 63 more also have this bundle.","id":"left_1","checkId":"checkfeature_1",
        "featureList":[
            {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/icon/57e0aff95cba2a27d6af277f/Comments.svg","featureNameH3":"Comments","featureNameP":"0.8 Week","featureNameH4":"₹14,273.88"}
        ]
    },
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd270c88f3ac56ef461c61/Productivity.jpg",
    "h3Name":"Productivity","span":"3 /","p":"23 features","bundleCount":"3/23","featureHeadH3":"Features (3/23)","featureTextH3":"Productivity","featureTextP":"","id":"left_2","checkId":"checkfeature_2",
    "featureList":[]
    },
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd270a88f3ac56ef461c60/CustomerInsight.jpg",
    "h3Name":"Customer Insight","span":"2 /","p":"7 features","bundleCount":"2/7","featureHeadH3":"Features (2/7)","featureTextH3":"Customer Insight","featureTextP":"Apps like Yelp, Urban Company (formerly UrbanClap) and 31 more also have this bundle.","id":"left_3","checkId":"checkfeature_3",
    "featureList":[]
    }

] 
export const mobileData=[
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/57e0aff95cba2a27d6af2781/Videos.png","h4":"Videos","id":"3056","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd272788f3ac56ef461c6a/PhotosVideos.jpg","h3":"Photos & Videos","p":"23 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/59fd158a88f3ac61106b3122/Trending.png","h4":"Trending","id":"2943","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd272f88f3ac56ef461c6d/Social.jpg","h3":"Social","p":"59 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/585898455cba2a5441cce8ea/Subscriptions.png","h4":"Subscriptions","id":"2708","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd272f88f3ac56ef461c6d/Social.jpg","h3":"Social","p":"59 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/5c5000b81f0c64172a7f77b2/splash_screen_mob.jpg","h4":"Splash Screen","id":"2667","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd274188f3ac56ef461c73/Essentials.jpg","h3":"Essentials","p":"42 features","bundleH4":"₹135.60K/₹1,149.05K"},
    {"img":"https://assets-builder.s3-ap-southeast-1.amazonaws.com/backend_default_feature.png","h4":"Sorting","id":"2649","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd274188f3ac56ef461c73/Essentials.jpg","h3":"Essentials","p":"42 features","bundleH4":"₹135.60K/₹1,149.05K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/57e0aff95cba2a27d6af2783/Share.png","h4":"Share","id":"2585","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd272f88f3ac56ef461c6d/Social.jpg","h3":"Social","p":"59 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/583e6f7a5cba2a4656829ce8/Settings.png","h4":"Settings","id":"2584","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd273288f3ac56ef461c6e/InventoryManagement.jpg","h3":"Inventory Management","p":"12 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/57e0aff95cba2a27d6af2782/Search.png","h4":"Search","id":"2547","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd274188f3ac56ef461c73/Essentials.jpg","h3":"Essentials","p":"42 features","bundleH4":"₹135.60K/₹1,149.05K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/583682215cba2a0b7f77747c/Reviews.png","h4":"Reviews","id":"2435","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd270a88f3ac56ef461c60/CustomerInsight.jpg","h3":"Customer Insight","p":"7 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/5c5000bc1f0c64172a7f7894/notavailable_mobile.png","h4":"Restore Purchase","id":"2423","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd272a88f3ac56ef461c6b/FinancePayments.jpg","h3":"Finance & Payments","p":"18 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/5c5000bf1f0c64172a7f791a/preview_mob.png","h4":"Preview Video","id":"2163","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd272788f3ac56ef461c6a/PhotosVideos.jpg","h3":"Photos & Videos","p":"23 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/59fd166488f3ac61106b35e1/Playlist.png","h4":"Playlist","id":"2106","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd271288f3ac56ef461c63/AudioMusic.jpg","h3":"Audio & Music","p":"11 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/59fd151b88f3ac61106b3096/Phone-verification.png","h4":"Phone Verification","id":"2087","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd272d88f3ac56ef461c6c/SecurityPrivacy.jpg","h3":"Security & Privacy","p":"30 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/5836826f5cba2a0b7f77747d/Payment.png","h4":"Payments","id":"2064","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd272a88f3ac56ef461c6b/FinancePayments.jpg","h3":"Finance & Payments","p":"18 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/5c5000ba1f0c64172a7f77ec/notification_settings_mob.png","h4":"Notification Settings","id":"1904","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd273888f3ac56ef461c70/ProjectManagement.jpg","h3":"Project Management","p":"9 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/57e0aff95cba2a27d6af2785/Notifications.png","h4":"Notifications","id":"1905","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd271888f3ac56ef461c65/Notifications.jpg","h3":"Alerts & Notifications","p":"9 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/5c5000ba1f0c64172a7f7810/navigation_menu_mob.png","h4":"Navigation Menu","id":"1876","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd270c88f3ac56ef461c61/Productivity.jpg","h3":"Productivity","p":"23 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/57e0aff95cba2a27d6af277e/Location.png","h4":"Location","id":"1658","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd272d88f3ac56ef461c6c/SecurityPrivacy.jpg","h3":"Security & Privacy","p":"30 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/5c5000bb1f0c64172a7f782c/language_options_mob.png","h4":"Language Options","id":"1586","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd270c88f3ac56ef461c61/Productivity.jpg","h3":"Productivity","p":"23 features","bundleH4":"₹0.00K/₹0.00K"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/android_image/5c5000b81f0c64172a7f77be/sign_in_with_google_mob.png","h4":"Google Login","id":"1346","bundleImg":"https://duj87royd3ze0.cloudfront.net/uploads/feature_bundle/background/59fd270a88f3ac56ef461c60/CustomerInsight.jpg","h3":"Customer Insight","p":"7 features","bundleH4":"₹0.00K/₹0.00K"}
    
   
]
export const webData=[
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/57e0aff95cba2a27d6af2781/videos.png","h4":"Videos","id":"3056"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/59fd158a88f3ac61106b3122/Trending-Web.png","h4":"Trending","id":"2943"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/585898455cba2a5441cce8ea/Subscriptions-Web.png","h4":"Subscriptions","id":"2708"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/5c5000b81f0c64172a7f77b2/splash_screen_web.jpg","h4":"Splash Screen","id":"2667"},
    {"img":"https://assets-builder.s3-ap-southeast-1.amazonaws.com/default-images/web+Backend+feature.png","h4":"Sorting","id":"2649"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/57e0aff95cba2a27d6af2783/Share-Web.png","h4":"Share","id":"2585"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/583e6f7a5cba2a4656829ce8/Settings.png","h4":"Settings","id":"2584"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/57e0aff95cba2a27d6af2782/Elastic-Search.png","h4":"Search","id":"2547"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/583682215cba2a0b7f77747c/Reviews.png","h4":"Reviews","id":"2435"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/5c5000bc1f0c64172a7f7894/notavailable_web.png","h4":"Restore Purchase","id":"2423"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/5c5000bf1f0c64172a7f791a/preview_web.png","h4":"Preview Video","id":"2163"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/59fd166488f3ac61106b35e1/Playlist.png","h4":"Playlist","id":"2106"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/59fd151b88f3ac61106b3096/Phone-Verification-Web.png","h4":"Phone Verification","id":"2087"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/5836826f5cba2a0b7f77747d/Payments-Web.png","h4":"Payments","id":"2064"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/5c5000ba1f0c64172a7f77ec/notification_settings_web.png","h4":"Notification Settings","id":"1904"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/57e0aff95cba2a27d6af2785/Notifications-web.png","h4":"Notifications","id":"1905"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/5c5000ba1f0c64172a7f7810/navigation_menu_web.png","h4":"Navigation Menu","id":"1876"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/57e0aff95cba2a27d6af277e/Location.png","h4":"Location","id":"1658"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/5c5000bb1f0c64172a7f782c/language_options_web.png","h4":"Language Options","id":"1586"},
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/web_image/5c5000b81f0c64172a7f77be/google_2B_login_web.png","h4":"Google Login","id":"1346"}
    
    
   
]
export const carouselDescription=[
    {"img":"https://duj87royd3ze0.cloudfront.net/uploads/feature/icon/57e0aff95cba2a27d6af2781/Videos.svg","id":"3056","carouselH4":"Videos - ₹28,547.77 (1.5 weeks)","webViewP":"Basic controls for uploaded video files: pause, play, volume control. Gives users more control over their vide ","P":"Basic controls for uploaded video files: pause, play, volume control. Gives users more control over their videos without having to exit the product. ","mobileViewP":"Basic controls for uploaded video files: pause, play, volume control. Gives user "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/59fd158a88f3ac61106b3122/Trending.svg","id":"2943","carouselH4":"Trending - ₹7,605.72 (0.4 week)","webViewP":"Users can discover what's popular within the product, grouped by the categories you choose. Useful for making  ","P":"Users can discover what's popular within the product, grouped by the categories you choose. Useful for making sure they don't miss what's interesting and relevant.  ","mobileViewP":"Users can discover what's popular within the product, grouped by the categories  "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/585898455cba2a5441cce8ea/Subscriptions.svg","id":"2708","carouselH4":"Subscriptions - ₹7,605.72 (0.4 week)","webViewP":"Make a message appear which invites a user to subscribe to your content with an email address. This can be int ","P":"Make a message appear which invites a user to subscribe to your content with an email address. This can be integrated to an admin console or CRM, to manage subscriptions from one place. ","mobileViewP":"Make a message appear which invites a user to subscribe to your content with an  "},
    {"img":"https://studio.builder.ai/assets/images/featureDefault.png","id":"2667","carouselH4":"Splash Screen - ₹2,376.79 (0.4 week)","webViewP":"The first thing a user sees when they open the product. Shows and reassures them that it's loading/starting. ","P":"The first thing a user sees when they open the product. Shows and reassures them that it's loading/starting. ","mobileViewP":"The first thing a user sees when they open the product. Shows and reassures them that it's loading/starting. "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/59fd157488f3ac61106b30eb/Sorting.svg","id":"2649","carouselH4":"Sorting - ₹7,605.72 (0.4 week)","webViewP":"Sort content based on criteria contained inside the product. Helps users quickly find what they need. Example: ","P":"Sort content based on criteria contained inside the product. Helps users quickly find what they need. Example: Sorting from 'low' to 'high' rating, A-Z, price. ","mobileViewP":"Sort content based on criteria contained inside the product. Helps users quickly "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/57e0aff95cba2a27d6af2783/Share.svg","id":"2585","carouselH4":"Share - ₹28,521.46 (1.5 weeks)","webViewP":"Users can take images, videos and content published within the product, and share them on their social media c ","P":"Users can take images, videos and content published within the product, and share them on their social media channels or by email. Makes it quicker and easier to reach new audiences who aren't using the product. ","mobileViewP":"Users can take images, videos and content published within the product, and share them on their social media c "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/583e6f7a5cba2a4656829ce8/Settings.svg","id":"2584","carouselH4":"Settings - ₹19,014.31 (1.1 weeks)","webViewP":"A list of common settings for the product. These are: Change password, deactivate account, edit profile.  ","P":"A list of common settings for the product. These are: Change password, deactivate account, edit profile.  ","mobileViewP":"A list of common settings for the product. These are: Change password, deactivate account, edit profile.  "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/57e0aff95cba2a27d6af2782/Search.svg","id":"2547","carouselH4":"Search - ₹28,521.46 (1.5 weeks)","webViewP":"Enter search queries and see related results from your database. Users can click/tap on results to view the re ","P":"Enter search queries and see related results from your database. Users can click/tap on results to view the result in more detail. ","mobileViewP":"Enter search queries and see related results from your database. Users can click "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/583682215cba2a0b7f77747c/Reviews.svg","id":"2435","carouselH4":"Reviews - ₹14,260.73 (0.8 week)","webViewP":"Users can write reviews and add star ratings for items listed in the product. Other users can read the reviews ","P":"Users can write reviews and add star ratings for items listed in the product. Other users can read the reviews, and see average ratings for each item. ","mobileViewP":"Users can write reviews and add star ratings for items listed in the product. Ot "},
    {"img":"https://studio.builder.ai/assets/images/featureDefault.png","id":"2423","carouselH4":"Restore Purchase - ₹23,292.53 (0.8 week)","webViewP":"A feature that allows you to transfer in-app purchases to other devices ","P":"A feature that allows you to transfer in-app purchases to other devices ","mobileViewP":"A feature that allows you to transfer in-app purchases to other devices "},
    {"img":"https://studio.builder.ai/assets/images/featureDefault.png","id":"2163","carouselH4":"Preview Video - ₹20,915.74 (1.5 weeks)","webViewP":"Show a short preview of a video inside the product. These can act as trailers to help and attract users when t ","P":"Show a short preview of a video inside the product. These can act as trailers to help and attract users when they're browsing.  ","mobileViewP":"Show a short preview of a video inside the product. These can act as trailers to "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/59fd166488f3ac61106b35e1/Playlist.svg","id":"2106","carouselH4":"Playlist - ₹7,605.72 (0.4 week)","webViewP":"Users can arrange a list of files to be played in order or shuffled. Playlists can be saved for use as referen ","P":"Users can arrange a list of files to be played in order or shuffled. Playlists can be saved for use as reference libraries. ","mobileViewP":"Users can arrange a list of files to be played in order or shuffled. Playlists c "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/59fd151b88f3ac61106b3096/PhoneVerification.svg","id":"2087","carouselH4":"Phone Verification - ₹7,605.72 (0.4 week)","webViewP":"Send a verification code to a user's phone before they can create an account/login. Adds an extra layer of sec ","P":"Send a verification code to a user's phone before they can create an account/login. Adds an extra layer of security, and the phone number can be another way to communicate. ","mobileViewP":"Send a verification code to a user's phone before they can create an account/log "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/5836826f5cba2a0b7f77747d/Payments.svg","id":"2064","carouselH4":"Payments - ₹28,521.46 (1.5 weeks)","webViewP":"A system for accepting and processing credit/debit payments, with transaction histories and payment status. Us  ","P":"A system for accepting and processing credit/debit payments, with transaction histories and payment status. Users add their card details, giving them control and making purchases simpler and faster.  ","mobileViewP":"A system for accepting and processing credit/debit payments, with transaction hi "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/57e0aff95cba2a27d6af2785/Notification.svg","id":"1904","carouselH4":"Notifications - ₹19,014.31 (1.1 weeks)","webViewP":"A dashboard for users to view and manage (including reply, mark, delete) notifications of activity. Shows unre ","P":"A dashboard for users to view and manage (including reply, mark, delete) notifications of activity. Shows unread notifications to highlight what's recent and encourages users to open and see what's been received. ","mobileViewP":"A dashboard for users to view and manage (including reply, mark, delete) notific "},
    {"img":"https://studio.builder.ai/assets/images/featureDefault.png","id":"1905","carouselH4":"Notification Settings - ₹20,915.74 (1.5 weeks)","webViewP":"Users can configure how and when notifications are received. Users can then better control their experience of ","P":"Users can configure how and when notifications are received. Users can then better control their experience of using the product. ","mobileViewP":"Users can configure how and when notifications are received. Users can then bett "},
    {"img":"https://studio.builder.ai/assets/images/featureDefault.png","id":"1876","carouselH4":"Navigation Menu - ₹20,915.74 (1.5 weeks)","webViewP":"Show a navigation menu on mobile devices that's different to a navigation menu on desktops. Remove or add menu ","P":"Show a navigation menu on mobile devices that's different to a navigation menu on desktops. Remove or add menu options depending on what you want users to see on different sized screens. ","mobileViewP":"Show a navigation menu on mobile devices that's different to a navigation menu o "},
    {"img":"https://bstudio-assets.azureedge.net/assets-builder/uploads/feature/icon/57e0aff95cba2a27d6af277e/Location.svg","id":"1658","carouselH4":"Location - ₹14,260.73 (0.8 week)","webViewP":"Users can check-in when they've arrived at a location, or edit their location. Useful for finding friends, or  ","P":"Users can check-in when they've arrived at a location, or edit their location. Useful for finding friends, or letting businesses know when potential customers are nearby. ","mobileViewP":"Users can check-in when they've arrived at a location, or edit their location. U "},
    {"img":"https://studio.builder.ai/assets/images/featureDefault.png","id":"1586","carouselH4":"Language Options - ₹18,538.95 (1.5 weeks)","webViewP":"Users have the option to change the language used, based on how many translations are supplied. Makes the prod ","P":"Users have the option to change the language used, based on how many translations are supplied. Makes the product open to more users from more regions.  ","mobileViewP":"Users have the option to change the language used, based on how many translation "},
    {"img":"https://studio.builder.ai/assets/images/featureDefault.png","id":"1346","carouselH4":"Google Login - ₹9,507.15 (0.8 week)","webViewP":"Users can login using their Google account details. No need to remember usernames and passwords. ","P":"Users can login using their Google account details. No need to remember usernames and passwords. ","mobileViewP":"Users can login using their Google account details. No need to remember usernames and passwords. "}
    
]